# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  LukkelEngine_config = debug
endif
ifeq ($(config),release)
  LukkelEngine_config = release
endif
ifeq ($(config),dist)
  LukkelEngine_config = dist
endif

PROJECTS := LukkelEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

LukkelEngine:
ifneq (,$(LukkelEngine_config))
	@echo "==== Building LukkelEngine ($(LukkelEngine_config)) ===="
	@${MAKE} --no-print-directory -C . -f LukkelEngine.make config=$(LukkelEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f LukkelEngine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   LukkelEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"